//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::{
    brand::Entity as Brand, cart::Entity as Cart, comment::Entity as Comment,
    license_capacity::Entity as LicenseCapacity, order::Entity as Order,
    order_item::Entity as OrderItem, order_template::Entity as OrderTemplate,
    product::Entity as Product, product_attribute::Entity as ProductAttribute,
    product_category::Entity as ProductCategory, shop::Entity as Shop,
    shop_bill_daily::Entity as ShopBillDaily, shop_employee::Entity as ShopEmployee,
    shop_order::Entity as ShopOrder, shop_product::Entity as ShopProduct,
    shop_setting_delivery::Entity as ShopSettingDelivery,
    shop_setting_financial::Entity as ShopSettingFinancial, shop_verify::Entity as ShopVerify,
    user::Entity as User, user_3rd_account::Entity as User3rdAccount,
    user_address::Entity as UserAddress, user_auth::Entity as UserAuth,
    user_auth_log::Entity as UserAuthLog, user_license::Entity as UserLicense,
    user_license_active_log::Entity as UserLicenseActiveLog,
    user_order_refund::Entity as UserOrderRefund, user_payment::Entity as UserPayment,
    user_profile::Entity as UserProfile,
};
