//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shop_bill_daily")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub shop_id: u32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub income: Decimal,
    pub date: Date,
    pub ver: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
