//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shop_verify")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub shop_id: u32,
    pub owner_id: u32,
    pub verify_type: u32,
    pub owner_corp: String,
    pub owner_corp_code: String,
    pub owner_corp_file: String,
    pub owner_corp_address: String,
    pub owner_corp_tel: String,
    pub owner_corp_fax: String,
    pub owner_name: String,
    pub owner_phone: String,
    pub owner_email: String,
    pub owner_id_card: String,
    pub owner_id_card_front: String,
    pub owner_id_card_back: String,
    pub owner_id_card_hand_front: String,
    pub owner_id_card_hand_back: String,
    pub verify_status: u32,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
