[package]
name = "rs-scripts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rs-scripts"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "3.1.5", features = ["derive"] }

