version: "3"

tasks:
  init:
    - echo "init"

  run:scripts:
    cmds:
      - cargo run --bin rs-scripts -- -n "Henry"

  #
  # parse env vars:
  #
  run:eth:scanner:
    cmds:
      - echo "run:eth scanner"
      - cargo run --bin rs-eth-scanner -- scan ${INFURA_RPC_URL} ${ETH_ADDRESS} ${TX_TYPE} ${TX_COUNT}

  run:binance:
    cmds:
      - echo "run:binance api tool"
      - cargo run --bin rs-binance -- auth ${BINANCE_API_KEY} ${BINANCE_SECRET_KEY}

  run:binance:market:
    cmds:
      - echo "run:binance api tool"
      - cargo run --bin rs-binance -- market empty



  run:discord:
    cmds:
      - echo "run discord bot"
      - cargo run --bin discord-bot -- -h