[workspace]
members = [
    "crates/basic",
    "crates/rs-cms",
    "crates/rs-leetcode",
    "crates/rs-scripts",
    "crates/rust-by-example",
    "crates/rust-programming-in-action",
    "crates/rust-programming-cookbook",
    #    "packages/axum/axum-axum-v0.4.5",
]