version: "3"

tasks:
  init:
    - echo "init"

  install:
    cmds:
      - cargo install cargo-watch  # auto compile and run:
      - cargo install diesel_cli

  run:
    cmds:
      - echo "run cms"
      - RUST_BACKTRACE=1 cargo run

  # auto compile and run:
  watch:
    cmds:
      - cargo watch -x run

  clean:
    cmds:
      - cargo clean

  open:
    cmds:
      - open http://localhost:3000

  docs:
    cmds:
      - open https://github.com/tokio-rs/axum
      - open https://github.com/diesel-rs/diesel
      - open https://diesel.rs/
      - open https://crates.io/crates/tracing


  ###############################################################################

  db:setup:
    cmds:
      - diesel setup

  db:add:
    cmds:
      - diesel migration generate posts

  # create tables:
  db:init:
    cmds:
      - diesel migration run

  db:redo:
    cmds:
      - diesel migration redo

  # delete all tables:
  db:revert:
    cmds:
      - diesel migration revert

  db:reset:
    cmds:
      - diesel database reset

  db:help:
    cmds:
      - diesel help

  db:show:
    cmds:
      - diesel print-schema
