version: "3"

tasks:
  init:
    - echo "init"

  install:
    - cargo install cargo-watch  # auto compile and run:

  run:
    cmds:
      - echo "run cms"
      - cargo run

  # auto compile and run:
  watch:
    - cargo watch -x run

  open:
    cmds:
      - open http://localhost:3000

  docs:
    cmds:
      - open https://github.com/tokio-rs/axum
      - open https://github.com/diesel-rs/diesel
      - open https://diesel.rs/
      - open https://crates.io/crates/tracing

