//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub mod prelude;

pub mod brand;
pub mod cart;
pub mod comment;
pub mod license_capacity;
pub mod order;
pub mod order_item;
pub mod order_template;
pub mod product;
pub mod product_attribute;
pub mod product_category;
pub mod shop;
pub mod shop_bill_daily;
pub mod shop_employee;
pub mod shop_order;
pub mod shop_product;
pub mod shop_setting_delivery;
pub mod shop_setting_financial;
pub mod shop_verify;
pub mod user;
pub mod user_3rd_account;
pub mod user_address;
pub mod user_auth;
pub mod user_auth_log;
pub mod user_license;
pub mod user_license_active_log;
pub mod user_order_refund;
pub mod user_payment;
pub mod user_profile;
