//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub product_id: u32,
    pub lang_id: u32,
    pub attr_key: String,
    pub attr_key_name: String,
    pub attr_value: String,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
