version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing
  #  OUT_DIR: "/Users/dev/Documents/iSpace/better-go/matrix/app/try/volo-example"
  DATABASE_URL: "sqlite:tmp/app.db"

# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:git:
    cmds:
      - cargo run --bin rs-git

  run:tpl:
    cmds:
      - cargo run --bin rs-tpl

  run:dir:
    cmds:
      - cargo run --bin rs-dir

  run:file:
    cmds:
      - cargo run --bin rs-file

  run:progress:
    cmds:
      - cargo run --bin rs-progress

  run:gent:
    cmds:
      - cargo run --bin rs-gent

  ################################################################################################


  install:
    cmds:
      - cargo install sqlx-cli # ref: https://github.com/launchbadge/sqlx/tree/main/sqlx-cli
      - cargo install sea-orm-cli # ref: https://www.sea-ql.org/SeaORM/docs/generate-entity/sea-orm-cli/

  init:db:
    cmds:
      - sqlx database drop
      - sqlx database create

  migrate:add:
    cmds:
      - sqlx migrate add app # 生成 db migration 文件, 手动编辑, 再执行 db 表创建+初始化

  migrate:
    cmds:
      - sqlx migrate run

  run:sql:
    cmds:
      - cargo run --bin rs-sql add "todo description"  # add
      - cargo run --bin rs-sql done 1 # change status
      - cargo run --bin rs-sql                         # list all

  ################################################################################################

  migrate:orm:init:
    cmds:
      - sea-orm-cli migrate init -d {{.APP_NAME}}
    #      - sea-orm-cli migrate generate create -d {{.APP_NAME}}  # generate empty migration file
    vars:
      APP_NAME: "migration"

  migrate:orm:model:
    cmds:
      - sea-orm-cli generate entity -u ${DATABASE_URL} -o {{.APP_NAME}}/src
      - cd {{.APP_NAME}}; cargo init --lib;
      - cd {{.APP_NAME}}; mv src/mod.rs src/lib.rs;
      - cd {{.APP_NAME}}; cargo add serde@1 --features derive
      - cd {{.APP_NAME}}; cargo add sea-orm@0.9
    vars:
      APP_NAME: "entity"
    ignore_error: true

  run:orm:
    cmds:
      - RUST_LOG=debug cargo run --bin rs-orm


  ################################################################################################

  update:
    cmds:
      - cargo update

  build:
    cmds:
      - cargo build

  clean:
    cmds:
      - cargo clean
