# curl -i http://httpbin.org/ip
GET http://httpbin.org/ip



###

# curl --request POST
#  --url http://127.0.0.1:5001/todos/add
#  --header 'Content-Type: application/json'
#  --data '{
#"text": "test"
#}'
POST http://127.0.0.1:5001/todos/add
Content-Type: application/json

{
    "text": "test"
}

###








###

# curl --request POST
#  --url http://127.0.0.1:5001/todos/add
#  --header 'Content-Type: application/json'
#  --data '{
#"text": "test"
#}'
POST http://127.0.0.1:5001/todos/add
Content-Type: application/json

{
    "text": "test"
}

###




### Send POST request with json body
POST http://127.0.0.1:5001/todos/add
#Content-Type: application/json
Content-Type: application/x-www-form-urlencoded

{
    "id": 999,
    "text": "test1"
}

### Send POST request with json body
POST http://127.0.0.1:5001/user/add
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### Send POST request with json body

POST https://httpbin.org/post
Content-Type: application/json

{
    "id": 999,
    "value": "content"
}


###
GET http://127.0.0.1:5001/user/add
Content-Type: application/x-www-form-urlencoded

username=jim&email=jim@gmail.com&password=test1

###
POST http://localhost:80/api/item
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"

field-value
--WebAppBoundary--

###



###

POST http://localhost:5000

{
    username:"test"
    email:"test@example.com",
password:"test password"
}
