version: "3"

tasks:
  init:
    cmds:
      - echo "init"

  dev:
    cmds:
      - echo "dev install"
      - cargo install --force cargo-edit

  run:
    cmds:
      - echo "run"
      - cargo run

  build:
    - echo "build"
    #    - cargo build --release
    - cargo build

  test:
    - echo "test"
    - cargo test

  release:
    cmds:
      - echo "release"
      - cargo build --release

  fix:
    cmds:
      - cargo metadata --verbose --format-version 1 --all-features
