version: "3"

tasks:
  init:
    - echo "init"
    - mkdir -p src/pb

  dev:
    - echo "dev install"
    - cargo install --force cargo-edit

  generate:
    - echo "generate protobuf"

  run:
    - task: run:server

  run:server:
    - cargo run --bin helloworld-server

  run:client:
    - cargo run --bin helloworld-client

  run:server2:
    - cargo run --bin helloworld-server2

  run:client2:
    - cargo run --bin helloworld-client2

  build:
    - echo "build"
    #    - cargo build --release
    - cargo build

  test:
    - echo "test"
    - cargo test

  release:
    cmds:
      - echo "release"
      - cargo build --release
      - cd ../..; open target/release/

  fix:
    cmds:
      - cargo metadata --verbose --format-version 1 --all-features
