version: "3"

tasks:
  init:
    - echo "init"
    - mkdir -p src/pb

  dev:
    - echo "dev install"
    - cargo install --force cargo-edit

  generate:
    - echo "generate protobuf"

  run:
    - cargo run --bin helloworld-server

  run:client:
    - cargo run --bin helloworld-client

  build:
    - echo "build"
#    - cargo build --release
    - cargo build

  test:
    - echo "test"
    - cargo test

  release:
    cmds:
      - echo "release"
      - cargo build --release
      - cd ../..; open target/release/
