// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Debug: typeof import('./src/components/debug/Debug.vue')['default']
    DebugButton: typeof import('./src/components/debug/DebugButton.vue')['default']
    DebugTab: typeof import('./src/components/debug/DebugTab.vue')['default']
    Demo: typeof import('./src/components/demo/Demo.vue')['default']
    Drawer: typeof import('./src/components/drawer/Drawer.vue')['default']
    Hello: typeof import('./src/components/demo/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings/Settings.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
