version: "3"

tasks:
  init:
    - echo "init"

  dev:
    cmds:
      - echo "dev install"
      - cargo install --force cargo-edit
      - cargo install --locked cargo-outdated

  dev:fe:
    cmds:
      - pnpm i -D vue-router@4
      - pnpm i -D unplugin-vue-components
      - pnpm i -D naive-ui
      - pnpm i -D vfonts
      - pnpm i -D @vicons/ionicons5

  install:
    cmds:
      - pnpm i
      - cd src-tauri/; cargo outdated
      - cd src-tauri/; cargo upgrade
      - cd src-tauri/; cargo build

  run:
    cmds:
      - pnpm dev

  test:
    cmds:
      - echo "test"
      - cd src-tauri; cargo test

  release:
    cmds:
      - echo "release"
      - pnpm build

  # generate app icon
  icon:
    cmds:
#      - pnpm add -D @tauri-apps/cli
      - pnpm tauri icon ./public/logo2.png

  fix:
    cmds:
      - cargo metadata --verbose --format-version 1 --all-features
