version: "3"

includes:
  notify:
    aliases: [ "n" ]
    taskfile: ./try-notify/
    dir: ./try-notify/
    optional: true


################################################################################################

tasks:
  run:
    cmds:
      - task: run:server
