version: "3"

tasks:
  init:
    - echo "init"

  dev:
    - echo "dev install"
    - cargo install --force cargo-edit
    - cargo install --force cbindgen
    - cargo add --build cbindgen

  generate:
    - echo "generate c bindings"
    - cbindgen --config cbindgen.toml --crate rs-ffi-core --output ./target/rs_ffi_core_header.h

  build:
    - echo "build"
    - cargo build --release


  test:
    - echo "test"
    - cargo test

  release:
    cmds:
      - echo "release"
      - cargo build --release
      - cd ../..; open target/release/

  install:
    cmds:
      - echo "install the local build binary to ~/.cargo/bin."
      - cargo install --path . --force --verbose
      - cargo install --list
      - cd ../..; open target/release/
