//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cart")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub buyer_id: u32,
    pub store_id: u32,
    pub store_name: String,
    pub product_id: u32,
    pub product_title: String,
    pub product_image: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub product_price: Decimal,
    pub product_amount: u32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub product_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub product_total: Decimal,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
