//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "order_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub mid: u32,
    #[sea_orm(unique)]
    pub order_no: String,
    pub merchant_id: u32,
    pub product_id: u32,
    pub product_type: u8,
    pub product_sku: u32,
    pub product_title: String,
    pub product_num: u32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub product_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub product_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub cost: Decimal,
    pub status: i32,
    pub ver: i32,
    pub ctime: DateTimeUtc,
    pub mtime: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
