//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shop_setting_delivery")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub shop_id: u32,
    #[sea_orm(unique)]
    pub delivery_id: u32,
    pub name: String,
    pub description: String,
    pub is_default: i8,
    pub delivery_type: u32,
    pub delivery_scope: u32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub delivery_fee: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub delivery_free_fee: Decimal,
    pub delivery_free_fee_type: u32,
    pub delivery_free_fee_count: u32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub delivery_free_fee_weight: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub delivery_free_fee_volume: Decimal,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
