//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shop_setting_financial")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub shop_id: u32,
    pub owner_id: u32,
    pub bank_no: String,
    pub bank_name: String,
    pub bank_branch: String,
    pub bank_account_name: String,
    pub bank_account_address: String,
    pub bank_account_phone: String,
    pub bank_account_identity_no: String,
    pub alipay_account: String,
    pub alipay_name: String,
    pub wechat_account: String,
    pub wechat_name: String,
    pub paypal_account: String,
    pub paypal_name: String,
    pub eth_address: String,
    pub usdt_address: String,
    pub btc_address: String,
    pub doge_address: String,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
