name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    #
    # install rust nightly:
    #
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
      with:
        profile: minimal
        toolchain: nightly
        components: clippy
        override: true

    # task:
    - name: Build
      run: cargo +nightly build --verbose

    - name: Run tests
      run: cargo +nightly test --verbose
